# Generated by Django 2.2.7 on 2019-11-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedEmbeds',
        ),
    ]
